DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS portfolio;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE portfolio (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticker TEXT NOT NULL,
  quantity DECIMAL NOT NULL,
  is_crypto INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);