DROP TABLE IF EXISTS portfolio;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE portfolio (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL REFERENCES "user" (id),
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticker TEXT NOT NULL,
  quantity DECIMAL(18, 8) NOT NULL,
  is_crypto BOOLEAN NOT NULL
);