name: Daily Email Sender

on:
  schedule:
    - cron: '0 11 * * *'  # Daily at 11:00 UTC
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_email_flow
        working-directory: backend
        env:
          DB_URL: ${{ secrets.DB_URL }}
          RECIPIENTEMAIL: ${{ secrets.RECIPIENTEMAIL }}
          SMTPUSERNAME: ${{ secrets.SMTPUSERNAME }}
          SMTPPASSWORD: ${{ secrets.SMTPPASSWORD }}
          APIKEYCRYPTO: ${{ secrets.APIKEYCRYPTO }}
          APIKEYSTOCK: ${{ secrets.APIKEYSTOCK }}
          REDDITCLIENTID: ${{ secrets.REDDITCLIENTID }}
          REDDITCLIENTSECRET: ${{ secrets.REDDITCLIENTSECRET }}
          REDDITUSERAGENT: ${{ secrets.REDDITUSERAGENT }}
          TWITTERBEARERTOKEN: ${{ secrets.TWITTERBEARERTOKEN }}
          CSRFSECRETKEY: ${{ secrets.CSRFSECRETKEY }}
          PERCENTAGECHANGETIME: ${{ secrets.PERCENTAGECHANGETIME }}
          SENTIMENTANALYSIS: ${{ secrets.SENTIMENTANALYSIS }}
        run: python run_generate_email.py
