name: Daily Email Sender

on:
  schedule:
    - cron: '0 11 * * *'  # Daily at 11:00 UTC (1 PM CEST / 12 PM CET)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies for lxml
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      # NEW PATCH FOIL PACKAGE STEP
      - name: Patch and install foil package from source
        run: |
          # Clone foil repo (replace with official repo URL if available)
          git clone https://github.com/joelgombin/foil.git
          cd foil

          # Patch setup.py or wheel metadata to fix invalid wheel filename tags
          # For demonstration, we do a simple sed to replace comma+space with dot
          # You might need to adjust depending on exact source
          sed -i 's/py36, py35/py36.py35/g' setup.py || echo "No setup.py patch needed"

          # Install foil from local source without building wheel
          python -m pip install --no-build-isolation --no-binary=:all: .

          cd ..

      - name: Install other dependencies
        run: pip install -r docker/requirements.txt --no-deps

      - name: Run generate_email_flow
        run: python .github/workflows/run_generate_email.py
        env:
          DB_URL: ${{ secrets.DB_URL }}
          RECIPIENTEMAIL: ${{ secrets.RECIPIENTEMAIL }}
          SMTPUSERNAME: ${{ secrets.SMTPUSERNAME }}
          SMTPPASSWORD: ${{ secrets.SMTPPASSWORD }}
          APIKEYCRYPTO: ${{ secrets.APIKEYCRYPTO }}
          APIKEYSTOCK: ${{ secrets.APIKEYSTOCK }}
          REDDITCLIENTID: ${{ secrets.REDDITCLIENTID }}
          REDDITCLIENTSECRET: ${{ secrets.REDDITCLIENTSECRET }}
          REDDITUSERAGENT: ${{ secrets.REDDITUSERAGENT }}
          TWITTERBEARERTOKEN: ${{ secrets.TWITTERBEARERTOKEN }}
          CSRFSECRETKEY: ${{ secrets.CSRFSECRETKEY }}
          PERCENTAGECHANGETIME: ${{ secrets.PERCENTAGECHANGETIME }}
          SENTIMENTANALYSIS: ${{ secrets.SENTIMENTANALYSIS }}
