name: Daily Email Sender

on:
  schedule:
    - cron: '0 11 * * *'  # Daily at 11:00 UTC (1 PM CEST / 12 PM CET)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies for lxml
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r docker/requirements.txt

      - name: Run generate_email_flow
        run: python .github/workflows/run_generate_email.py
        env:
          DB_URL: ${{ secrets.DB_URL }}
          RECIPIENTEMAIL: ${{ secrets.RECIPIENTEMAIL }}
          SMTPUSERNAME: ${{ secrets.SMTPUSERNAME }}
          SMTPPASSWORD: ${{ secrets.SMTPPASSWORD }}
          APIKEYCRYPTO: ${{ secrets.APIKEYCRYPTO }}
          APIKEYSTOCK: ${{ secrets.APIKEYSTOCK }}
          REDDITCLIENTID: ${{ secrets.REDDITCLIENTID }}
          REDDITCLIENTSECRET: ${{ secrets.REDDITCLIENTSECRET }}
          REDDITUSERAGENT: ${{
