name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Add Conda to system path
      shell: bash
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Initialize Conda
      shell: bash
      run: source $CONDA/etc/profile.d/conda.sh

    - name: Upgrade pip, setuptools, and wheel
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Create and activate Conda environment
      shell: bash
      run: |
        conda create -y -n myenv python=3.9
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        echo "CONDA_ENV_ACTIVE=true" >> $GITHUB_ENV
        python --version  # Confirm Python 3.9

    - name: Install dependencies
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        conda install -y pip flake8 pytest
        pip install --upgrade pip setuptools wheel
        pip install -r docker/requirements.txt || true
        pip install python-dotenv click supabase pydapper psycopg2-binary flask requests praw vaderSentiment prettytable

    - name: Verify Installed Packages
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        pip freeze | grep foil
        python --version

    - name: Lint with flake8
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        pytest
